# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

#Giving the name of the action
name: API Test Framework Executuion

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    #cron job always run on utc time
  schedule:
    - cron: 00 20 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    #Giving permision to read and write
    permissions: 
      contents: read
      checks: write
      issues: write
      
    steps:
    - uses: actions/checkout@v4
    #Setup java 11 whic is similar to local
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        #Here we are giving command names and commands
    - name: Execute Test
      run: mvn clean test -Dsuite=suite -X

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3

      with:
       name: Logs
       path: logs/

    #Giving junit report path here
    - name: publish report
      if: always()
      uses: dorny/test-reporter@v1
      with:
         name: testNG results
         path: target/surefire-reports/junitreports/TEST-*.xml
         reporter: java-junit
       
